project:
  type: website
  output-dir: _site

website:
  title: "liamco.io"
  navbar:
    right:
      - contact-me.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true

editor: visual


