project:
  type: website
  output-dir: _site

website:
  title: "liamco.io"
  navbar:
    right:
      - certs.qmd
      - contact-me.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    toc-depth: 5

editor: visual


