project:
  type: website
  output-dir: _site

website:
  title: "liamco.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lico27

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true

editor: visual


